"""initial migration

Revision ID: 1fa2db4bec11
Revises: d4d96b30970d
Create Date: 2024-11-08 22:01:58.710966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fa2db4bec11'
down_revision = 'd4d96b30970d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('content_analysis', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('user_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('relevant_content', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_responses',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_responses')
    op.drop_table('user_classifications')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
